/* FA1 Revision Hub — content (IGCSE aligned to portions). Expand here freely. */
window.ORDER = ["ict","phys","chem","econ","math","eng","fr"];
window.DATA = {

/* ================= ICT · 0417 · Ch5 + 6.1–6.5 ================= */
ict:{name:"ICT",code:"0417 · Ch5 + 6.1–6.5",blurb:"Effects of IT + Applications",
 papers:[{name:"Past papers (CIE 0417)",url:"https://pastpapers.co/cie/?dir=IGCSE/ICT-0417"}],
 cards:[
  {t:"5·Home",f:"Two groups of home microprocessor devices",b:"<b>Labour-saving:</b> washing machine, microwave, cooker, dishwasher, robot vacuum, bread-maker, smart fridge. <b>Other:</b> alarm clock, TV, central heating/AC, phones, entertainment."},
  {t:"5·Home",f:"Positive effects of labour-saving devices",b:"<ul><li>More leisure time; no need to stay home while cooking/washing</li><li>Control remotely via smartphone</li><li>Burglar alarms = security</li><li>Smart fridges order food / reduce waste</li></ul>"},
  {t:"5·Home",f:"Negative effects of home devices",b:"<ul><li>Lazy / less fit</li><li>Lose household skills</li><li>Over-reliance on ready meals</li><li>Cybersecurity risk; standby wastes power</li></ul>"},
  {t:"5·Home",f:"General adv of ALL microprocessor devices",b:"Save energy (switch off after inactivity) · easier to 'program' than manual knobs (e.g. scan a QR code so the oven sets its programme)."},
  {t:"5·Home",f:"General disadv of ALL devices",b:"Wasteful society (thrown away when circuit board fails) · harder for technophobes · standby wastes electricity."},
  {t:"5·Home",f:"Data-security risk of smart devices",b:"Can be hacked (default/no password). Hacker learns holiday dates (→break-in) or steals card data from fridge orders. Fix: unique strong passwords + updates."},
  {t:"5·Home",f:"Effect on social interaction",b:"<b>+</b> friends via chat rooms, shared interests, cheap VoIP. <b>−</b> less face-to-face (isolation), anxiety meeting people, cyberbullying."},
  {t:"5·Transport",f:"Where microprocessors are used in transport",b:"Motorway traffic monitoring · congestion zones · ANPR · automatic traffic lights · air-traffic control · railway signalling."},
  {t:"5·Transport",f:"Smart motorways",b:"Central computer controls signs/traffic, redirects around accidents. Risk: hacking = control of the road network."},
  {t:"5·Transport",f:"Advantages of transport monitoring/control",b:"<ul><li>Reduce jams / journey time</li><li>More efficient (more vehicles)</li><li>ANPR penalises offences + spots stolen cars</li><li>Less human error → fewer accidents</li></ul>"},
  {t:"5·Transport",f:"Disadvantages (incl. ANPR)",b:"<ul><li>Hacker disruption</li><li>System failure = standstill</li><li>ANPR tracks innocent people (privacy)</li></ul>"},
  {t:"5·Transport",f:"How an autonomous car works",b:"Sensors (radar/ultrasonic) + cameras build a 3D image; microprocessor signals actuators to brake, steer, change gear. Red light: recognise sign → brake+park → monitor → go on green."},
  {t:"5·Transport",f:"Autonomous vehicles — advantages",b:"Safer (human error removed) · better for environment · less congestion, more lane capacity · shorter journeys · self-parking."},
  {t:"5·Transport",f:"Autonomous vehicles — disadvantages",b:"Expensive to set up · fear of hacking / software glitches · sensors fail in snow, cameras need cleaning · driver reluctance · job losses (taxis)."},
  {t:"5·Transport",f:"Autonomous trains",b:"Use LiDaR (lasers → 3D image), proximity + infrared sensors, GPS, actuators (speed, braking, doors). Adv: punctual, fewer staff, safer, energy-efficient."},
  {t:"5·Health",f:"RSI — cause + fixes",b:"Repeated fine movements (typing/clicking). Fix: wrist rest · breaks · ergonomic keyboard/mouse · voice software."},
  {t:"5·Health",f:"Back & neck — fixes",b:"Ergonomic chair · footrest · monitor at eye level · correct posture / stretch."},
  {t:"5·Health",f:"Eyestrain — fixes",b:"Anti-glare screen · window blinds · LCD/LED (no flicker) · eyes tested · adjust brightness · don't sit too close."},
  {t:"5·Health",f:"Headaches — fixes",b:"Anti-glare screen · adjust brightness · blue-light glasses · eyes tested. <b>NOT 'take breaks'.</b>"},
  {t:"6.1",f:"The 5 communication media",b:"Newsletters/posters · websites · multimedia presentations · media streaming · e-publications."},
  {t:"6.1",f:"Steps to make a newsletter (word processor)",b:"Open WP → get photos (camera/internet/scan) → save to file → import → crop/resize → type/import text → position + wrap → proofread → save."},
  {t:"6.1",f:"Why spell-check may be wrong",b:"Different dialect (UK/US) · names/proper nouns flagged · similar-sounding words (where/were/wear) · word not in dictionary."},
  {t:"6.1",f:"Website vs poster — adv & disadv",b:"<b>+</b> sound/video/animation, hyperlinks, global reach, easy update. <b>−</b> can be hacked/pharming, needs internet, less portable."},
  {t:"6.1",f:"Multimedia presentations",b:"Slides with sound, video, animation, transitions — good for a large audience, but need hardware (projector) and can fail."},
  {t:"6.1",f:"Media streaming",b:"Audio/video played as it downloads (buffering) — no need to store the whole file first."},
  {t:"6.1",f:"E-publications",b:"Digital books/magazines/newspapers on a device — searchable, portable, can include multimedia, cheaper than print; but need a device."},
  {t:"6.2",f:"What is a computer model?",b:"A computer-generated model of a real system (often a spreadsheet) to study and predict its behaviour."},
  {t:"6.2",f:"Why use a model (the exam 4)",b:"<b>Cheaper · quicker · safer</b> than the real thing, and you can <b>change variables / test 'what-ifs'</b> (space, nuclear, crash tests)."},
  {t:"6.2",f:"Disadvantages of models + examples",b:"Only as good as the data/program; can be costly; people may distrust results. Examples: finance, flood, traffic, weather, bridge design."},
  {t:"6.3",f:"Microprocessor control chain",b:"Read sensor → compare to preset → if over, signal actuator (act) → if under, signal actuator (act) → continuous."},
  {t:"6.3",f:"Sensor vs actuator (+ examples)",b:"Sensor measures (temperature, light, pressure, distance, humidity, pH); actuator acts (motor, valve, heater)."},
  {t:"6.3",f:"Robots — advantages",b:"Work in hazardous environments · 24/7, no wages/holidays · consistent · productive · do boring repetitive tasks · swap end-effectors."},
  {t:"6.3",f:"Robots — disadvantages",b:"Bad at unusual/one-off tasks · cause unemployment / lost skills · factories can relocate · expensive to set up & maintain."},
  {t:"6.3",f:"How robots are programmed",b:"(1) a sequence of instructions, (2) a human guides the arm and each movement is stored, or (3) a worker wears sensors and movements are recorded."},
  {t:"6.4",f:"School management system tasks",b:"Registration & attendance · student performance tracking · computer-aided learning (CAL)."},
  {t:"6.4",f:"Automate registration + methods",b:"Magnetic-stripe ID card + reader · RFID/contactless · biometrics (fingerprint). Card stores school, name, DOB, unique ID."},
  {t:"6.4",f:"Benefit of electronic registration",b:"Attendance known at all times (secure in a fire) · a student can't 'register then leave' · accurate records for parents/teachers."},
  {t:"6.4",f:"Student performance & CAL",b:"Track grades/progress and flag issues. CAL software adapts to the learner, gives instant feedback, lets them work at their own pace."},
  {t:"6.5",f:"How online booking works",b:"Pick event/date/seat → seat flagged/locked instantly in the database → pay → confirmed (e-ticket) → shows unavailable to everyone else."},
  {t:"6.5",f:"Online booking — advantages",b:"Prevents double-booking · book 24/7 from anywhere · see/choose available seats · instant confirmation · cheaper (fewer staff)."},
  {t:"6.5",f:"Online booking — disadvantages",b:"Needs computer + internet · downtime = no bookings · booking/transaction fees · card data at risk if hacked."},
  {t:"6.5",f:"Where online booking is used",b:"Flights / trains / buses · theatre & cinema · concerts · sporting events · hotels."},
 ],
 quiz:[
  {q:"NOT a way to reduce headaches?",o:["Anti-glare screen","Take regular breaks","Adjust brightness","Eyes tested"],a:1,w:"Breaks = RSI/eyestrain, not headaches."},
  {q:"Device that carries out an action in control systems:",o:["Sensor","Actuator","Modem","Router"],a:1,w:"Actuators act; sensors measure."},
  {q:"Best reason to model a bridge on computer:",o:["Computers are accurate","Safer & cheaper, and test 'what-ifs'","Looks professional","Works 24/7"],a:1,w:"Cheaper·quicker·safer·change variables."},
  {q:"Online booking stops double-booking by…",o:["Phoning customers","Flagging/locking the seat in the database","Emailing a warning","First-come by post"],a:1,w:"Immediate DB lock."},
  {q:"A disadvantage of ANPR:",o:["Fewer accidents","Innocent people can be tracked","Spots stolen cars","Penalises offences"],a:1,w:"Privacy — others are advantages."},
  {q:"Autonomous trains build a 3D image using…",o:["ANPR","LiDaR lasers","OMR","Spell check"],a:1,w:"LiDaR = lasers → 3D map."},
  {q:"A website advantage over a poster:",o:["Costs more","Sound/video/hyperlinks + global reach","Local only","Needs reprinting"],a:1,w:"Multimedia + global + easy update."},
  {q:"First step of the microprocessor control chain:",o:["Signal actuator","Read data from the sensor","Apply brakes","Store online"],a:1,w:"Read → compare → signal → act → repeat."},
  {q:"A benefit of electronic registration:",o:["Cheaper paper","Attendance known at all times (fire-safe)","Nicer handwriting","No computers"],a:1,w:"Can't register-then-leave."},
  {q:"Media streaming means…",o:["Download whole file first","Play as it downloads (buffering)","Print a doc","Scan a form"],a:1,w:"Plays as it arrives."},
  {q:"Which reduces RSI?",o:["Anti-glare screen","Ergonomic chair","Wrist rest","Window blinds"],a:2,w:"Wrist rest = RSI."},
  {q:"Which reduces back/neck problems?",o:["Voice software","Footrest + monitor at eye level","Blue-light glasses","Wrist rest"],a:1,w:"Posture fixes."},
  {q:"A method to automate registration:",o:["Paper register","RFID / biometric card","Whiteboard","Phone call"],a:1,w:"RFID / magnetic stripe / fingerprint."},
  {q:"A negative social effect of home devices:",o:["Cheaper VoIP","Social isolation / cyberbullying","New hobbies","New friends"],a:1,w:"Isolation is the negative."},
  {q:"An advantage of robots over humans:",o:["Handle one-off tasks well","Work in hazardous areas 24/7","Cheap to buy","No maintenance"],a:1,w:"Hazardous + non-stop."},
  {q:"An autonomous car's radar + cameras are used to…",o:["Play music","Build a 3D image of surroundings","Charge the battery","Book a service"],a:1,w:"They're its 'eyes and ears'."},
  {q:"A disadvantage of online booking:",o:["Prevents double-booking","Needs internet / can go down","24/7 access","Choose your seat"],a:1,w:"Others are advantages."},
  {q:"Why might spell-check flag a correct word?",o:["It's a name/proper noun","It fixes grammar","It adds images","It changes fonts"],a:0,w:"Names, dialect, or not-in-dictionary."},
 ],
 fixes:[
  {fix:"Wrist rest",c:["rsi"],n:"Supports wrists — RSI only."},
  {fix:"Ergonomic chair",c:["back"],n:"Back/neck only."},
  {fix:"Anti-glare screen",c:["eye","head"],n:"Glare → both eyestrain & headaches."},
  {fix:"Take regular breaks",c:["rsi","back","eye"],n:"NOT credited for headaches!"},
  {fix:"Adjust brightness to room",c:["eye","head"],n:"Both screen problems."},
  {fix:"Footrest",c:["back"],n:"Posture = back/neck."},
  {fix:"Voice-recognition software",c:["rsi"],n:"Less typing = RSI."},
  {fix:"Monitor at eye level",c:["back"],n:"Neck posture = back/neck."},
  {fix:"Blue-light glasses",c:["eye","head"],n:"Screen fix — eyestrain & headaches."},
  {fix:"Ergonomic keyboard",c:["rsi"],n:"Wrist strain = RSI."},
  {fix:"Window blinds",c:["eye"],n:"Classic eyestrain answer."},
  {fix:"Have eyes tested",c:["eye","head"],n:"Vision fix — both."},
  {fix:"LCD/LED screen (no flicker)",c:["eye"],n:"Reduces eyestrain."},
  {fix:"Keep screen clean/dust-free",c:["eye","head"],n:"Both screen problems."},
 ],
 scen:[
  {q:"A manual flood system relies on PEOPLE watching rising water. Why computerise?",o:["Works 24/7, doesn't get sick","Sensors respond faster AND watchers aren't put in danger","More accurate than humans","Accessed remotely"],a:1,w:"Scenario = people in danger → 'faster + not in danger'. '24/7' is generic."},
  {q:"Why MODEL a flood defence instead of building it?",o:["Computers are accurate","Cheaper, quicker, safer + change variables","Works continuously","Saves staff time"],a:1,w:"Modelling always: cheaper·quicker·safer·change variables."},
  {q:"Robots spray-paint cars instead of humans because…",o:["Cheaper to buy","Work in harmful fumes + identical consistent results","They're intelligent","Never break down"],a:1,w:"Hazardous + consistency. 'Cheaper to buy' is false."},
  {q:"A band wants WORLDWIDE fans to hear a new song. Best medium?",o:["Printed wall poster","A website with the song embedded (global + audio)","Local newsletter","Local paper notice"],a:1,w:"Global reach + multimedia = website."},
  {q:"Specific security risk of a smart fridge that auto-orders food?",o:["Gets too cold","Hacker steals stored payment/card data","Food goes off","Uses more power"],a:1,w:"It pays online → card data is the specific risk."},
  {q:"A privacy campaigner objects to ANPR. Their valid concern?",o:["Too slow","Innocent people's movements can be tracked","Wastes power","Can't read plates"],a:1,w:"ANPR's specific disadvantage is tracking/privacy."},
  {q:"School swaps paper registers for ID cards. Specific benefit?",o:["Faster than people","Can't 'register then leave' — known in a fire","Saves electricity","Data can be emailed"],a:1,w:"Attendance/security is the scenario."},
 ]
},

/* ================= PHYSICS · 0625 ================= */
phys:{name:"Physics",code:"0625 · Unit 1 + Energy",blurb:"Forces, pressure, energy",
 papers:[{name:"Past papers (CIE 0625)",url:"https://pastpapers.co/cie/?dir=IGCSE/Physics-0625"},{name:"Topic questions (Save My Exams)",url:"https://www.savemyexams.com/igcse/physics/cie/"}],
 cards:[
  {t:"Moments",f:"Moment — definition & formula",b:"Turning effect of a force about a pivot. <b>Moment = force × perpendicular distance</b> from pivot. Unit: N·m."},
  {t:"Moments",f:"Everyday moment examples",b:"Door handle (force far from hinge), spanner, seesaw, scissors, crowbar, wheelbarrow — a longer distance gives a bigger moment for the same force."},
  {t:"Moments",f:"Principle of moments",b:"For a body in equilibrium: sum of clockwise moments = sum of anticlockwise moments about any pivot. F₁d₁ = F₂d₂."},
  {t:"Moments",f:"Two conditions for equilibrium",b:"1) No resultant force (up = down). 2) No resultant moment (clockwise = anticlockwise). Both must hold."},
  {t:"C. of Gravity",f:"Centre of gravity",b:"The point through which the whole weight of an object appears to act. For a uniform shape it's at the geometric centre."},
  {t:"C. of Gravity",f:"Finding the CG of an irregular lamina",b:"Hang it from a point, hang a plumb line, draw the vertical; repeat from another point — the CG is where the lines cross."},
  {t:"C. of Gravity",f:"Stability & toppling",b:"An object topples when the vertical line through its CG falls <b>outside its base</b>. More stable = low CG + wide base."},
  {t:"C. of Gravity",f:"3 types of equilibrium",b:"Stable (tilt → CG rises → returns) · Unstable (CG falls → topples) · Neutral (CG stays same height → stays put)."},
  {t:"Hooke's Law",f:"Hooke's Law",b:"Extension ∝ force, provided the limit of proportionality isn't exceeded. F = kx."},
  {t:"Hooke's Law",f:"Spring constant",b:"<b>k = F / x</b> (N/m). Measures stiffness. Extension = final − original length (never total length!)."},
  {t:"Hooke's Law",f:"Limit of proportionality",b:"The point beyond which force & extension are no longer proportional (the load–extension graph starts to curve)."},
  {t:"Hooke's Law",f:"Load–extension graph",b:"Straight line through origin up to the limit of proportionality; then curves. k = gradient of the straight part."},
  {t:"Pressure",f:"Pressure formula",b:"<b>p = F / A</b>. Unit: pascal (Pa) = N/m². Small area → high pressure (knife, drawing pin); large area → low pressure (skis, snowshoes)."},
  {t:"Pressure",f:"Pressure in a liquid",b:"<b>Δp = ρgΔh</b>. Increases with depth & density; acts equally in all directions; independent of container shape (dams are thicker at the base)."},
  {t:"Energy",f:"Energy stores",b:"Kinetic · gravitational potential · elastic (strain) · chemical · thermal (internal) · nuclear · electrostatic."},
  {t:"Energy",f:"Conservation of energy",b:"Energy cannot be created or destroyed, only transferred/stored. Total energy stays constant."},
  {t:"Energy",f:"Kinetic & potential energy",b:"<b>KE = ½mv²</b> · <b>ΔGPE = mgΔh</b> (g ≈ 10 N/kg). A falling object converts GPE → KE."},
  {t:"Energy",f:"Work done",b:"<b>Work = force × distance moved in the direction of the force</b> (W = Fd). Unit: joule (J). Work done = energy transferred."},
  {t:"Energy",f:"Power",b:"<b>Power = work done ÷ time</b> (P = W/t or E/t). Unit: watt (W) = joule per second."},
  {t:"Energy",f:"Efficiency",b:"<b>Efficiency = (useful energy output ÷ total energy input) × 100%</b>. No machine is 100% efficient (some energy is wasted, usually as heat)."},
  {t:"Energy",f:"Sankey diagrams",b:"Arrow width ∝ amount of energy. Input arrow splits into useful output + wasted energy. Wider useful arrow = more efficient."},
  {t:"Moments",f:"Why a door handle is far from the hinges",b:"The handle sits far from the pivot (hinges) → larger perpendicular distance → a bigger moment for the same push, so the door opens easily."},
  {t:"Moments",f:"Balancing a beam",b:"Adjust loads or distances until clockwise moment = anticlockwise moment. A heavier load must sit closer to the pivot to balance a lighter one further away."},
  {t:"C. of Gravity",f:"Real stability examples",b:"Racing cars are wide & low (very stable) · buses carry heavy loads low down · a person stands with feet apart to widen the base and lower toppling risk."},
  {t:"Hooke's Law",f:"Elastic vs plastic behaviour",b:"Elastic = returns to original length when the force is removed. Plastic (inelastic) = permanently deformed, which happens past the elastic limit."},
  {t:"Pressure",f:"Hydraulics",b:"Liquids are (nearly) incompressible and transmit pressure equally in all directions — a small force on a small piston gives a large force on a big piston (car brakes, jacks)."},
  {t:"Pressure",f:"Total pressure at depth",b:"Total pressure = atmospheric pressure + ρgΔh. The ρgΔh part is the extra pressure due to the liquid above you."},
  {t:"Energy",f:"GPE ↔ KE transfers",b:"A falling object: GPE → KE. A pendulum swaps GPE (at the top) and KE (at the bottom) continuously. Ignoring friction, total energy stays constant."},
  {t:"Energy",f:"How energy is transferred",b:"Four pathways: mechanically (a force does work), electrically (a current), by heating, and by radiation (e.g. light or sound waves)."},
  {t:"Energy",f:"Wasted energy",b:"In every transfer some energy is 'wasted' — dissipated to the surroundings, usually as heat (sometimes sound). That's why efficiency is never 100%."},
 ],
 quiz:[
  {q:"A 4 N force acts 0.5 m from a pivot. Moment?",o:["0.5 N·m","2 N·m","8 N·m","4.5 N·m"],a:1,w:"4 × 0.5 = 2 N·m."},
  {q:"Beam balances: 6 N at 0.3 m left; force at 0.2 m right =",o:["4 N","9 N","1.8 N","12 N"],a:1,w:"6×0.3 = F×0.2 → F = 9 N."},
  {q:"A spring extends 0.04 m under 8 N. Spring constant k?",o:["0.5 N/m","32 N/m","200 N/m","2 N/m"],a:2,w:"k = F/x = 8 ÷ 0.04 = 200 N/m."},
  {q:"Pressure of water at 3 m (ρ=1000, g=10)?",o:["300 Pa","3000 Pa","30 000 Pa","300 000 Pa"],a:2,w:"Δp = ρgΔh = 1000×10×3 = 30 000 Pa."},
  {q:"An object topples when the line through its CG…",o:["Is vertical","Falls outside its base","Rises","Is central"],a:1,w:"Outside the base → topples."},
  {q:"Extension is…",o:["Total length","Final − original length","Original length","Force ÷ area"],a:1,w:"Never use total length."},
  {q:"Unit of power:",o:["Joule","Newton","Watt","Pascal"],a:2,w:"Watt = joule per second."},
  {q:"Efficiency =",o:["input ÷ output","useful out ÷ total in × 100","work × time","force × distance"],a:1,w:"Useful energy out over total in."},
  {q:"Which is MORE stable?",o:["High CG, narrow base","Low CG, wide base","High CG, wide base","Tall & thin"],a:1,w:"Low CG + wide base."},
  {q:"Work lifting: 20 N through 3 m =",o:["6 J","23 J","60 J","0.15 J"],a:2,w:"W = Fd = 20×3 = 60 J."},
  {q:"KE of 2 kg at 3 m/s =",o:["6 J","9 J","18 J","3 J"],a:1,w:"½mv² = ½×2×9 = 9 J."},
  {q:"GPE gained lifting 5 kg by 2 m (g=10) =",o:["10 J","100 J","50 J","25 J"],a:1,w:"mgh = 5×10×2 = 100 J."},
  {q:"Pressure is highest with…",o:["Large area","Small area (same force)","Zero force","At the surface"],a:1,w:"p = F/A."},
  {q:"Power if 300 J transferred in 5 s =",o:["1500 W","60 W","305 W","0.017 W"],a:1,w:"P = 300 ÷ 5 = 60 W."},
  {q:"In a Sankey diagram the arrow width shows…",o:["Time","Amount of energy","Speed","Temperature"],a:1,w:"Width ∝ energy."},
  {q:"Which is NOT an energy store?",o:["Kinetic","Chemical","Elastic","Distance"],a:3,w:"Distance isn't an energy store."},
  {q:"Moment of 10 N acting 0.4 m from a pivot:",o:["2.5 N·m","4 N·m","40 N·m","0.04 N·m"],a:1,w:"10 × 0.4 = 4 N·m."},
  {q:"Pressure of 200 N over 0.5 m²:",o:["100 Pa","400 Pa","0.0025 Pa","250 Pa"],a:1,w:"p = F/A = 200 ÷ 0.5 = 400 Pa."},
  {q:"Machine: 60 J useful from 100 J input. Efficiency?",o:["40%","60%","100%","160%"],a:1,w:"60/100 × 100 = 60%."},
  {q:"Hydraulics work because liquids…",o:["Are compressible","Transmit pressure equally","Are magnetic","Store charge"],a:1,w:"Pressure is transmitted equally through a fluid."},
  {q:"A pendulum at its lowest point has mostly…",o:["GPE","KE","Chemical energy","Nuclear energy"],a:1,w:"GPE has converted to KE at the bottom."},
  {q:"Wasted energy is usually dissipated as…",o:["Light","Heat","Sound only","Nuclear"],a:1,w:"Mostly heat to the surroundings."},
  {q:"Total pressure at depth in a liquid =",o:["ρgΔh only","atmospheric + ρgΔh","F × A","mgh"],a:1,w:"Add atmospheric pressure."},
 ]
},

/* ================= CHEMISTRY · 0620 ================= */
chem:{name:"Chemistry",code:"0620 · Electricity + Stoichiometry",blurb:"Electrolysis + molar mass",
 papers:[{name:"Past papers (CIE 0620)",url:"https://pastpapers.co/cie/?dir=IGCSE/Chemistry-0620"},{name:"Topic questions (Save My Exams)",url:"https://www.savemyexams.com/igcse/chemistry/cie/"}],
 cards:[
  {t:"Electrolysis",f:"What is electrolysis?",b:"The breakdown of an ionic compound (molten or in aqueous solution) using electricity, into its elements."},
  {t:"Electrolysis",f:"Key terms",b:"<b>Electrolyte</b> = ionic compound that conducts. <b>Anode</b> = positive electrode. <b>Cathode</b> = negative electrode. <b>Inert</b> electrode = doesn't react (platinum/carbon)."},
  {t:"Electrolysis",f:"Which ion goes where?",b:"<b>Cations</b> (positive: metals/H⁺) → <b>cathode</b> (−). <b>Anions</b> (negative: non-metals) → <b>anode</b> (+). ('PANIC' — Positive Anode, Negative Is Cathode)."},
  {t:"Electrolysis",f:"Why do ionic compounds conduct?",b:"Only when molten or dissolved — the ions become free to move and carry charge. Solid ionic compounds do NOT conduct (ions fixed)."},
  {t:"Electrolysis",f:"Conductors vs insulators",b:"Metals & graphite conduct via free electrons. Ionic compounds conduct only when molten/aqueous (ions move). Covalent compounds don't conduct (no free charges)."},
  {t:"Electrolysis",f:"Molten lead(II) bromide",b:"Cathode: lead metal (Pb) forms. Anode: bromine gas (Br₂) forms. Metal at the cathode, non-metal at the anode."},
  {t:"Electrolysis",f:"At the electrodes (what forms)",b:"Cathode: positive metal ions gain electrons → metal (or H₂ from H⁺). Anode: negative ions lose electrons → non-metal (e.g. Br₂, O₂, Cl₂)."},
  {t:"Electrolysis",f:"Electroplating",b:"Coating an object with a metal using electrolysis — object = cathode, pure plating metal = anode, electrolyte = a salt of that metal. Improves appearance / prevents corrosion."},
  {t:"Electrolysis",f:"Uses of electrolysis",b:"Extracting reactive metals (e.g. aluminium), purifying copper, electroplating, producing chlorine/hydrogen."},
  {t:"Stoichiometry",f:"Relative atomic mass (Ar)",b:"The average mass of an atom of an element compared to 1/12 the mass of a carbon-12 atom. E.g. Ar(H)=1, C=12, O=16, Ca=40."},
  {t:"Stoichiometry",f:"Relative formula/molecular mass (Mr)",b:"Add the Ar of every atom in the formula. H₂O = (2×1)+16 = 18. CO₂ = 12+(2×16) = 44. NaCl = 23+35.5 = 58.5."},
  {t:"Stoichiometry",f:"Mr with brackets",b:"Multiply everything inside the bracket. Ca(OH)₂ = 40 + 2×(16+1) = 40 + 34 = <b>74</b>. Mg(NO₃)₂ = 24 + 2×(14+48) = 148."},
  {t:"Stoichiometry",f:"Moles & molar mass",b:"Molar mass = Mr in grams (g/mol). <b>moles = mass ÷ Mr</b>. E.g. 36 g water ÷ 18 = 2 mol; 44 g CO₂ ÷ 44 = 1 mol."},
  {t:"Stoichiometry",f:"Percentage by mass of an element",b:"<b>% = (Ar × number of atoms ÷ Mr) × 100</b>. E.g. %O in H₂O = 16 ÷ 18 × 100 = 88.9%."},
  {t:"Electrolysis",f:"Oxidation & reduction at electrodes",b:"Cathode = <b>reduction</b> (ions gain electrons). Anode = <b>oxidation</b> (ions lose electrons). OIL RIG: Oxidation Is Loss, Reduction Is Gain of electrons."},
  {t:"Electrolysis",f:"Electrolysis of aqueous solutions",b:"Cathode: a reactive metal ion stays in solution and H₂ is released; a less-reactive metal is deposited. Anode: a halide → the halogen; otherwise O₂."},
  {t:"Electrolysis",f:"Concentrated NaCl solution",b:"Cathode: hydrogen (H₂). Anode: chlorine (Cl₂). Solution left behind: sodium hydroxide (NaOH)."},
  {t:"Electrolysis",f:"Purification of copper",b:"Impure copper = anode (dissolves away) · pure copper = cathode (copper deposits on it) · electrolyte = copper(II) sulfate solution."},
  {t:"Electrolysis",f:"Extraction of aluminium",b:"By electrolysis of molten aluminium oxide (dissolved in cryolite to lower the melting point). Aluminium forms at the cathode, oxygen at the anode."},
  {t:"Stoichiometry",f:"Conservation of mass",b:"Total mass of reactants = total mass of products. Atoms are only rearranged, never created or destroyed — so equations must balance."},
  {t:"Stoichiometry",f:"More Mr practice",b:"CaCO₃ = 40+12+48 = 100 · H₂SO₄ = 2+32+64 = 98 · NaOH = 23+16+1 = 40 · MgO = 24+16 = 40."},
 ],
 quiz:[
  {q:"The positive electrode is the…",o:["Cathode","Anode","Electrolyte","Ion"],a:1,w:"Anode = positive."},
  {q:"Ionic compounds conduct when…",o:["Solid","Molten or in solution","Cold","Dry"],a:1,w:"Ions must be free to move."},
  {q:"Cations move to the…",o:["Anode","Cathode","Electrolyte","Air"],a:1,w:"Positive cations → negative cathode."},
  {q:"Mr of CO₂ (C=12, O=16):",o:["28","44","32","40"],a:1,w:"12 + (2×16) = 44."},
  {q:"Mr of H₂O (H=1, O=16):",o:["17","18","16","19"],a:1,w:"(2×1)+16 = 18."},
  {q:"Mr of Ca(OH)₂ (Ca=40,O=16,H=1):",o:["57","74","58","90"],a:1,w:"40 + 2(16+1) = 74."},
  {q:"Moles in 88 g of CO₂ (Mr 44):",o:["1","2","4","0.5"],a:1,w:"88 ÷ 44 = 2 mol."},
  {q:"Molten PbBr₂ — anode product:",o:["Lead","Bromine","Hydrogen","Oxygen"],a:1,w:"Anions (Br⁻) → anode → bromine."},
  {q:"An inert electrode is often…",o:["Sodium","Carbon/platinum","Copper","Iron"],a:1,w:"Graphite/platinum don't react."},
  {q:"moles =",o:["mass × Mr","mass ÷ Mr","Mr ÷ mass","mass + Mr"],a:1,w:"moles = mass ÷ Mr."},
  {q:"In electroplating, the object to be coated is the…",o:["Anode","Cathode","Electrolyte","Wire"],a:1,w:"Object = cathode; plating metal = anode."},
  {q:"Why doesn't solid NaCl conduct?",o:["No ions","Ions are fixed in place","It's a metal","It's a gas"],a:1,w:"Ions can't move until molten/dissolved."},
  {q:"Mass of 2 mol of water (Mr 18):",o:["9 g","18 g","36 g","20 g"],a:2,w:"mass = moles × Mr = 2×18 = 36 g."},
  {q:"Cathode product when electrolysing molten NaCl:",o:["Chlorine","Sodium","Oxygen","Hydrogen"],a:1,w:"Na⁺ → cathode → sodium metal."},
  {q:"Reduction happens at the…",o:["Anode","Cathode","Electrolyte","Wire"],a:1,w:"Cathode = reduction (gain of electrons)."},
  {q:"OIL RIG: reduction is…",o:["Loss of electrons","Gain of electrons","Loss of protons","Gain of neutrons"],a:1,w:"Reduction Is Gain of electrons."},
  {q:"Anode product, concentrated NaCl solution:",o:["Sodium","Chlorine","Hydrogen","Oxygen"],a:1,w:"Halide → halogen → chlorine."},
  {q:"Purifying copper: pure copper forms at the…",o:["Anode","Cathode","Electrolyte","Beaker"],a:1,w:"Deposits on the pure-copper cathode."},
  {q:"Mr of CaCO₃ (Ca=40,C=12,O=16):",o:["68","100","72","84"],a:1,w:"40+12+(3×16)=100."},
  {q:"Mr of H₂SO₄ (H=1,S=32,O=16):",o:["98","49","82","66"],a:0,w:"2+32+(4×16)=98."},
  {q:"Moles in 50 g CaCO₃ (Mr 100):",o:["0.5","2","5","50"],a:0,w:"50 ÷ 100 = 0.5 mol."},
  {q:"Aluminium is extracted by electrolysis of…",o:["Aluminium chloride solution","Molten aluminium oxide","Solid aluminium","Aluminium gas"],a:1,w:"Molten Al₂O₃ in cryolite."},
 ]
},

/* ================= ECONOMICS · 0455 ================= */
econ:{name:"Economics",code:"0455 · Unit 2.8–2.10",blurb:"Market, failure, mixed",
 papers:[{name:"Past papers (CIE 0455)",url:"https://pastpapers.co/cie/?dir=IGCSE/Economics-0455"},{name:"Topic questions (Save My Exams)",url:"https://www.savemyexams.com/igcse/economics/cie/"}],
 cards:[
  {t:"Market system",f:"Market economic system",b:"Resources allocated by the <b>price mechanism</b> (demand & supply) with private ownership and the profit motive. No government intervention."},
  {t:"Market system",f:"How the price mechanism allocates",b:"High demand → price rises → producers supply more (resources move to where they're most wanted); low demand → price falls → resources move away. Prices act as signals & incentives."},
  {t:"Market system",f:"Advantages of the market system",b:"<ul><li>Efficient — resources follow consumer demand</li><li>Wide consumer choice</li><li>Competition → lower prices + innovation</li><li>Profit incentive drives effort</li></ul>"},
  {t:"Market system",f:"Disadvantages of the market system",b:"<ul><li>Inequality (rich/poor gap)</li><li>Market failure — public goods not provided</li><li>Monopolies exploit consumers</li><li>Ignores social costs (pollution)</li></ul>"},
  {t:"Market failure",f:"What is market failure?",b:"When the market fails to allocate resources efficiently — society doesn't get the best outcome (too much or too little is produced/consumed)."},
  {t:"Market failure",f:"Causes of market failure",b:"Externalities · public goods · merit & demerit goods · monopoly power · information failure."},
  {t:"Market failure",f:"Externalities",b:"Effects on third parties not involved in the transaction. <b>Negative</b> = external cost (pollution, noise). <b>Positive</b> = external benefit (education, vaccination)."},
  {t:"Market failure",f:"Private vs social costs",b:"Private cost = cost to the producer/consumer. Social cost = private cost + external cost. Market ignores external costs → overproduction of harmful goods."},
  {t:"Market failure",f:"Merit vs demerit goods",b:"<b>Merit</b> = under-consumed, better than people realise (education, healthcare). <b>Demerit</b> = over-consumed, worse than realised (cigarettes, alcohol)."},
  {t:"Market failure",f:"Public goods",b:"Non-excludable (can't stop non-payers) + non-rival (one person's use doesn't reduce others') — e.g. street lighting, defence. Market won't provide → the government must."},
  {t:"Mixed system",f:"Mixed economic system",b:"Combines a private sector (market) with a public sector (government). Most real economies are mixed. The government corrects market failure."},
  {t:"Mixed system",f:"Why governments intervene",b:"Provide public goods · correct externalities · encourage merit / discourage demerit goods · reduce inequality · control monopolies."},
  {t:"Mixed system",f:"Methods of government intervention",b:"Taxes (on demerit goods / to cut pollution) · subsidies (on merit goods) · regulation & laws · direct state provision · price controls."},
  {t:"Mixed system",f:"Advantages of a mixed economy",b:"Gets market efficiency & choice, but the government provides public goods, reduces inequality, and fixes market failure — the 'best of both'."},
  {t:"Market failure",f:"Monopoly power",b:"When one firm dominates a market it can charge higher prices, restrict output and cut choice/quality — a source of market failure. Governments regulate monopolies."},
  {t:"Market failure",f:"Information failure",b:"Consumers or producers lack full information, so they make poor decisions (e.g. not knowing how harmful a demerit good is). Resources get misallocated."},
  {t:"Mixed system",f:"Advantages of government intervention",b:"Provides public goods · corrects externalities · protects consumers · reduces inequality · can stabilise the economy."},
  {t:"Mixed system",f:"Disadvantages of government intervention",b:"Can be costly, cause inefficiency, create 'government failure' (intervention makes things worse), and reduce incentives through high taxes/red tape."},
  {t:"Mixed system",f:"Nationalisation vs privatisation",b:"<b>Nationalisation</b> = the government takes over an industry (public sector). <b>Privatisation</b> = selling a state industry to private owners (private sector)."},
  {t:"Market system",f:"Consumer sovereignty",b:"Consumers 'vote' with their spending — producers make what sells. Consumer demand ultimately decides what is produced in a market."},
 ],
 quiz:[
  {q:"In a market economy resources are allocated by…",o:["The government","The price mechanism (demand & supply)","A committee","Chance"],a:1,w:"Price mechanism, private ownership."},
  {q:"Market failure means…",o:["A business goes bankrupt","Resources aren't allocated efficiently","Prices rise","A shop closes"],a:1,w:"Society doesn't get the best outcome."},
  {q:"Factory pollution is an example of…",o:["Positive externality","Negative externality","Public good","Subsidy"],a:1,w:"External cost on third parties."},
  {q:"A merit good is…",o:["Over-consumed & harmful","Under-consumed & beneficial (education)","Never traded","Free to make"],a:1,w:"Better for you than people realise."},
  {q:"Street lighting is a…",o:["Demerit good","Public good","Luxury good","Private good"],a:1,w:"Non-excludable + non-rival."},
  {q:"A mixed economy has…",o:["Only private firms","Only the state","Both private + public sectors","No money"],a:2,w:"Market + government together."},
  {q:"Government discourages a demerit good by…",o:["Subsidy","Tax","Advertising it","Ignoring it"],a:1,w:"Tax raises price → less consumed."},
  {q:"A disadvantage of the pure market system:",o:["Consumer choice","Inequality / market failure","Competition","Innovation"],a:1,w:"The others are advantages."},
  {q:"Government supports a merit good by…",o:["Taxing it","Subsidising it","Banning it","Nothing"],a:1,w:"Subsidy lowers price → more consumed."},
  {q:"Cigarettes are a…",o:["Merit good","Demerit good","Public good","Free good"],a:1,w:"Over-consumed, more harmful than realised."},
  {q:"Social cost =",o:["Private cost only","Private cost + external cost","External cost only","Zero"],a:1,w:"Includes third-party costs."},
  {q:"In the price mechanism, rising demand usually…",o:["Lowers price","Raises price → more supplied","Bans the good","Has no effect"],a:1,w:"Price signals resources to move in."},
  {q:"A public good is NOT provided by the market because…",o:["It's illegal","Non-payers can't be excluded (no profit)","It's too cheap","Nobody wants it"],a:1,w:"Non-excludable → no incentive to supply."},
  {q:"Which is a government intervention method?",o:["Price mechanism","Subsidy","Competition","Profit motive"],a:1,w:"Tax, subsidy, regulation, provision."},
  {q:"A monopoly can harm consumers by…",o:["Lowering prices","Charging higher prices + less choice","More competition","More innovation"],a:1,w:"Market power → higher prices."},
  {q:"Information failure means…",o:["Perfect information","Lacking information to decide well","No demand","No supply"],a:1,w:"Poor decisions → misallocation."},
  {q:"'Government failure' is when…",o:["Markets work perfectly","Intervention makes things worse","Firms make profit","Prices are stable"],a:1,w:"Intervention can misfire."},
  {q:"Privatisation means…",o:["Government takes over","Selling a state industry to private owners","Banning trade","Raising taxes"],a:1,w:"Public → private sector."},
  {q:"A negative externality example:",o:["Vaccination","Factory pollution","Education","Street lights"],a:1,w:"External cost on others."},
  {q:"Consumer sovereignty means…",o:["Government decides","Consumers' spending decides what's produced","Firms decide alone","No choice"],a:1,w:"Demand drives production."},
  {q:"Which corrects a negative externality?",o:["Subsidy","Tax on the polluter","Advertising","Nothing"],a:1,w:"Tax internalises the external cost."},
  {q:"Vaccination gives a benefit to others — this is a…",o:["Negative externality","Positive externality","Monopoly","Tax"],a:1,w:"External benefit."},
 ]
},

/* ================= MATHS · 0607 ================= */
math:{name:"Maths",code:"0607 · Ch12 + Ch13",blurb:"Mensuration + quadratics",
 papers:[{name:"Past papers (CIE 0607)",url:"https://pastpapers.papacambridge.com/papers/caie/igcse-cambridge-international-mathematics-0607"}],
 cards:[
  {t:"Mensuration",f:"Circle: area & circumference",b:"Area = <b>πr²</b> · Circumference = <b>2πr</b> (or πd)."},
  {t:"Mensuration",f:"Area of 2D shapes",b:"Triangle = ½·b·h · Parallelogram = b·h · Trapezium = ½(a+b)·h · Rectangle = l·w."},
  {t:"Mensuration",f:"Volume of a prism / cylinder",b:"Prism = cross-sectional area × length. Cylinder = <b>πr²h</b>. Cuboid = l·w·h."},
  {t:"Mensuration",f:"Volume of cone, sphere, pyramid",b:"Cone = ⅓πr²h · Sphere = <b>4⁄3 πr³</b> · Pyramid = ⅓ × base area × height."},
  {t:"Mensuration",f:"Surface areas",b:"Cylinder = 2πr² + 2πrh · Sphere = 4πr² · Cone (curved) = πrl (l = slant height)."},
  {t:"Mensuration",f:"Arc length & sector area",b:"Arc = (θ/360)·2πr · Sector area = (θ/360)·πr² (θ = angle at centre)."},
  {t:"Mensuration",f:"Units — area vs volume",b:"Area is in square units (cm², m²); volume in cubic units (cm³, m³). 1 m² = 10 000 cm²; 1 m³ = 1 000 000 cm³."},
  {t:"Mensuration",f:"Compound shapes",b:"Split into simple shapes (rectangles, triangles, semicircles), find each area/volume, then add or subtract."},
  {t:"Quadratics",f:"Standard form",b:"A quadratic is <b>ax² + bx + c = 0</b> (a ≠ 0). Its graph is a parabola; the solutions (roots) are where it crosses the x-axis."},
  {t:"Quadratics",f:"Factorising",b:"Find two numbers that multiply to <b>a·c</b> and add to <b>b</b>. e.g. x²+5x+6 = (x+2)(x+3), so x = −2 or −3."},
  {t:"Quadratics",f:"The quadratic formula",b:"For ax²+bx+c=0: <b>x = (−b ± √(b²−4ac)) / 2a</b>. Use when it won't factorise neatly."},
  {t:"Quadratics",f:"The discriminant (b²−4ac)",b:">0 → two real roots · =0 → one repeated root · <0 → no real roots."},
  {t:"Quadratics",f:"Completing the square",b:"x²+bx+c → (x + b/2)² − (b/2)² + c. Gives the minimum/turning point of the parabola."},
  {t:"Quadratics",f:"Reading a quadratic graph",b:"Roots = x-intercepts · y-intercept = c · vertex = turning point (min if a>0, max if a<0) · line of symmetry through the vertex."},
  {t:"Mensuration",f:"Hemisphere & total cone area",b:"Hemisphere volume = ⅔πr³. Total surface area of a solid cone = πrl + πr² (curved surface + circular base)."},
  {t:"Mensuration",f:"Pythagoras' theorem",b:"For a right-angled triangle: <b>a² + b² = c²</b> (c = hypotenuse). Used to find missing lengths, e.g. a cone's slant height."},
  {t:"Mensuration",f:"Volume unit conversions",b:"1 cm³ = 1000 mm³ · 1 m³ = 1 000 000 cm³ · 1 litre = 1000 cm³. Always check units match before calculating."},
  {t:"Quadratics",f:"Difference of two squares",b:"a² − b² = (a + b)(a − b). e.g. x² − 16 = (x+4)(x−4), so x = ±4."},
  {t:"Quadratics",f:"Solving by factorising",b:"Make it = 0 → factorise → set each bracket = 0. e.g. x²+2x−8=0 → (x+4)(x−2)=0 → x = −4 or 2."},
  {t:"Quadratics",f:"Shape of the parabola",b:"If a > 0 it opens upward (∪, has a minimum). If a < 0 it opens downward (∩, has a maximum)."},
 ],
 quiz:[
  {q:"Area of a circle radius 5 (π≈3.14):",o:["31.4","78.5","15.7","25"],a:1,w:"πr² = 3.14×25 = 78.5."},
  {q:"Volume of a cylinder =",o:["πr²","2πr","πr²h","4/3πr³"],a:2,w:"Base area × height."},
  {q:"x²+5x+6 factorises to…",o:["(x+1)(x+6)","(x+2)(x+3)","(x+5)(x+1)","(x−2)(x−3)"],a:1,w:"2×3=6, 2+3=5."},
  {q:"The discriminant is…",o:["2a","−b","b²−4ac","√b"],a:2,w:"b²−4ac decides the roots."},
  {q:"Volume of a sphere =",o:["πr²h","4πr²","4/3πr³","⅓πr²h"],a:2,w:"4/3 πr³."},
  {q:"If b²−4ac < 0 the equation has…",o:["2 real roots","1 root","No real roots","Infinite roots"],a:2,w:"Negative → no real solutions."},
  {q:"Circumference of a circle =",o:["πr²","2πr","½bh","πrl"],a:1,w:"2πr (or πd)."},
  {q:"Area of a trapezium =",o:["½bh","b·h","½(a+b)h","πr²"],a:2,w:"½(a+b)h."},
  {q:"Roots of a quadratic on a graph are…",o:["The y-intercept","Where it crosses the x-axis","The vertex","The gradient"],a:1,w:"x-intercepts = solutions."},
  {q:"Solve x²−9=0:",o:["x=3 only","x=±3","x=9","No solution"],a:1,w:"(x−3)(x+3) → x=±3."},
  {q:"Surface area of a sphere =",o:["4πr²","πr²","2πrh","4/3πr³"],a:0,w:"4πr²."},
  {q:"1 m² equals…",o:["100 cm²","1000 cm²","10 000 cm²","1 000 000 cm²"],a:2,w:"100×100 = 10 000 cm²."},
  {q:"Area of a triangle base 6, height 4:",o:["24","12","10","20"],a:1,w:"½×6×4 = 12."},
  {q:"Factorise x² − 16:",o:["(x−4)²","(x+4)(x−4)","(x+16)(x−1)","x(x−16)"],a:1,w:"Difference of two squares."},
  {q:"Volume of a cuboid 2×3×4:",o:["9","24","14","12"],a:1,w:"2×3×4 = 24."},
  {q:"Solve (x−2)(x+5)=0:",o:["x=2 or −5","x=−2 or 5","x=2 or 5","x=10"],a:0,w:"Each bracket = 0."},
  {q:"Hemisphere volume =",o:["4/3πr³","⅔πr³","πr²h","2πr³"],a:1,w:"Half a sphere = ⅔πr³."},
  {q:"Hypotenuse if the legs are 3 and 4:",o:["5","7","6","12"],a:0,w:"√(9+16) = 5."},
  {q:"If a<0, the parabola…",o:["Opens up (min)","Opens down (max)","Is a line","Is a circle"],a:1,w:"a<0 → ∩ shape, maximum."},
  {q:"Area of a circle, diameter 10 (π≈3.14):",o:["31.4","78.5","314","15.7"],a:1,w:"r=5 → πr² = 78.5."},
 ]
},

/* ================= ENGLISH · 0500 ================= */
eng:{name:"English",code:"0500 · Comprehension + Summary",blurb:"Reading technique",
 papers:[{name:"Past papers (CIE 0500)",url:"https://pastpapers.co/cie/?dir=IGCSE/English-First-Language-0500"}],
 cards:[
  {t:"Comprehension",f:"Comprehension golden rules",b:"<ul><li>Read the question first, then the text</li><li>Answer in your OWN words</li><li>Match the mark allocation (2 marks = 2 points)</li><li>Only answer what's asked — don't pad</li></ul>"},
  {t:"Comprehension",f:"Using your own words",b:"Reword ideas — don't lift whole phrases. Examiners reward understanding, not copying. Quote only when the question asks you to."},
  {t:"Comprehension",f:"Inference questions",b:"'What does this suggest/imply?' — read between the lines. Use evidence from the text but explain the underlying meaning, not just the literal words."},
  {t:"Comprehension",f:"'Explain the effect' questions",b:"Name the technique (word choice, imagery, metaphor) → give a short quote → explain the EFFECT on the reader. (Technique → example → effect.)"},
  {t:"Comprehension",f:"Selecting quotations",b:"Pick short, precise quotes — a few words, not whole sentences. The quote should directly support the point you're making."},
  {t:"Summary",f:"Summary writing — steps",b:"<ul><li>Identify only the RELEVANT points (highlight them)</li><li>Rewrite in your own words</li><li>No examples, repetition or opinions</li><li>Stay within the word limit</li></ul>"},
  {t:"Summary",f:"What loses summary marks",b:"Copying sentences · adding your opinion · including examples/quotes · going over the word limit · repeating a point."},
  {t:"Summary",f:"Points = marks",b:"Each distinct relevant point ≈ 1 mark. Pack in as many separate points concisely as possible — reward is for content, not elegance."},
  {t:"Summary",f:"Planning a summary",b:"Underline every relevant point first, number them, then write them in continuous prose (not a list) in your own words within the limit."},
  {t:"Writing",f:"Tone & audience",b:"Match register to purpose: formal for a report/letter, lively for a description. Keep it consistent throughout."},
  {t:"Comprehension",f:"Fact vs opinion",b:"A fact can be proven; an opinion is a belief or judgement. Look for evaluative words (best, terrible, should) that signal opinion."},
  {t:"Comprehension",f:"Vocabulary in context",b:"'What does X mean here?' — give the meaning as used in that sentence, not a dictionary definition. Use surrounding words as clues."},
  {t:"Comprehension",f:"Writer's purpose",b:"Ask: is the writer trying to inform, persuade, entertain, describe or advise? The purpose shapes the tone and word choice."},
  {t:"Comprehension",f:"Literal retrieval",b:"'According to the passage…' = find the answer stated directly in the text. Quick marks — locate it and reword it."},
  {t:"Comprehension",f:"Connotations",b:"Words carry feelings beyond their literal meaning ('cheap' vs 'affordable'). Comment on the effect the word choice creates."},
  {t:"Summary",f:"Combining points",b:"Merge related points into one concise sentence to save words — but never drop a separate mark-worthy point when you do."},
 ],
 quiz:[
  {q:"In a summary you should…",o:["Copy sentences","Rewrite relevant points in your own words","Add your opinion","Include examples"],a:1,w:"Own words, relevant points only."},
  {q:"A 3-mark comprehension question needs…",o:["1 point","3 separate points","A full essay","A quote"],a:1,w:"Match marks to points."},
  {q:"Which LOSES summary marks?",o:["Using own words","Staying in the word limit","Adding examples & opinions","Concise points"],a:2,w:"No examples/opinions in a summary."},
  {q:"'Use your own words' means…",o:["Copy the text","Reword the idea","Quote it","Translate it"],a:1,w:"Show understanding by rewording."},
  {q:"To explain how a writer creates tension you…",o:["Summarise the plot","Name technique + quote + effect","Give your opinion","Count the words"],a:1,w:"Technique → example → effect."},
  {q:"Best FIRST step for a summary:",o:["Start writing","Highlight the relevant points","Count words","Add a conclusion"],a:1,w:"Find relevant points before writing."},
  {q:"A good quotation is…",o:["A whole paragraph","Short and precise","Made up","The question itself"],a:1,w:"A few well-chosen words."},
  {q:"An inference question asks you to…",o:["Copy a line","Read between the lines / explain implied meaning","Count words","Give a title"],a:1,w:"Explain the underlying meaning."},
  {q:"A summary should be written as…",o:["A bullet list","Continuous prose in your own words","A poem","A diagram"],a:1,w:"Continuous prose, own words."},
  {q:"Register should match the…",o:["Word count","Purpose & audience","Author's name","Page number"],a:1,w:"Formal vs lively as appropriate."},
  {q:"'It was the worst film ever' is…",o:["A fact","An opinion","A quote","A summary"],a:1,w:"Evaluative → opinion."},
  {q:"'Vocabulary in context' means give…",o:["A dictionary definition","The meaning as used in that sentence","A synonym list","The word's origin"],a:1,w:"Meaning in context."},
  {q:"A persuasive text's purpose is to…",o:["List facts only","Convince the reader","Confuse","Count words"],a:1,w:"Persuade."},
  {q:"'According to the passage' wants you to…",o:["Give your opinion","Retrieve what's stated in the text","Predict the ending","Rate the writer"],a:1,w:"Literal retrieval."},
  {q:"Word connotations are…",o:["Literal meanings only","The feelings a word carries","Spelling rules","Punctuation"],a:1,w:"Emotional/associative meaning."},
  {q:"To save words in a summary you…",o:["Repeat points","Combine related points concisely","Add examples","Add opinions"],a:1,w:"Merge, stay concise."},
 ]
},

/* ================= FRENCH · 0520 ================= */
fr:{name:"French",code:"0520 · Units 1–4",blurb:"Tenses + vocab",
 papers:[{name:"Past papers (CIE 0520)",url:"https://pastpapers.co/cie/?dir=IGCSE/French-0520"}],
 cards:[
  {t:"Présent",f:"Present tense — regular endings",b:"<b>-ER</b> (parler): e, es, e, ons, ez, ent. <b>-IR</b> (finir): is, is, it, issons, issez, issent. <b>-RE</b> (vendre): s, s, —, ons, ez, ent."},
  {t:"Présent",f:"Key irregular present verbs",b:"être (suis, es, est, sommes, êtes, sont) · avoir (ai, as, a, avons, avez, ont) · aller (vais, vas, va, allons, allez, vont) · faire (fais, fais, fait, faisons, faites, font)."},
  {t:"Présent",f:"Reflexive verbs",b:"Add the reflexive pronoun: je <b>me</b> lève, tu <b>te</b> laves, il <b>se</b> couche, nous <b>nous</b> levons, vous <b>vous</b> lavez, ils <b>se</b> couchent."},
  {t:"Passé composé",f:"Passé composé — formation",b:"<b>avoir/être (present) + past participle</b>. -ER→é (parlé), -IR→i (fini), -RE→u (vendu). J'ai mangé = I ate / have eaten."},
  {t:"Passé composé",f:"Être verbs + agreement",b:"Movement/change verbs use ÊTRE (DR MRS VANDERTRAMP: aller, venir, monter, rester…). The participle <b>agrees</b>: elle est allée, ils sont allés."},
  {t:"Passé composé",f:"Common irregular participles",b:"avoir→eu · être→été · faire→fait · voir→vu · prendre→pris · boire→bu · lire→lu · écrire→écrit · mettre→mis."},
  {t:"Futur proche",f:"Futur proche (near future)",b:"<b>aller (present) + infinitive</b> = 'going to…'. Je vais manger = I'm going to eat. Nous allons partir = we're going to leave."},
  {t:"Grammar",f:"Negatives",b:"<b>ne … pas</b> around the verb: je <b>ne</b> mange <b>pas</b>. Others: ne…jamais (never), ne…rien (nothing), ne…plus (no more)."},
  {t:"Grammar",f:"Adjective agreement",b:"Adjectives agree with the noun: petit / petite / petits / petites. Most go AFTER the noun (une voiture rouge); BAGS adjectives go before."},
  {t:"Grammar",f:"Asking questions",b:"3 ways: rising intonation (Tu viens?) · <b>est-ce que</b> (Est-ce que tu viens?) · inversion (Viens-tu?). Question words: qui, que, où, quand, comment, pourquoi, combien."},
  {t:"Grammar",f:"Giving opinions",b:"je pense que… (I think that) · à mon avis (in my opinion) · je trouve que… · j'aime / je n'aime pas / je préfère + noun or infinitive."},
  {t:"Vocab",f:"Bien-être physique (health)",b:"la santé (health) · le sommeil (sleep) · faire du sport · manger sainement (eat healthily) · fatigué(e) (tired) · le stress · se détendre (relax)."},
  {t:"Vocab",f:"Les études (studies)",b:"les devoirs (homework) · l'emploi du temps (timetable) · une matière (subject) · réussir (to succeed) · un examen (exam) · la note (grade)."},
  {t:"Vocab",f:"La vie quotidienne (daily life)",b:"se lever (get up) · se coucher (go to bed) · d'habitude (usually) · le matin / le soir · prendre le petit déjeuner (have breakfast)."},
  {t:"Vocab",f:"Les endroits (places)",b:"la ville (town) · le quartier (neighbourhood) · à la campagne (in the countryside) · le centre commercial (mall) · la gare (station)."},
  {t:"Vocab",f:"Connectives (link words)",b:"et (and) · mais (but) · parce que (because) · donc (so) · aussi (also) · cependant (however) · d'abord / ensuite / enfin (first/then/finally)."},
  {t:"Grammar",f:"Articles",b:"Definite: le / la / l' / les (the). Indefinite: un / une / des (a/some). They must match the noun's gender & number."},
  {t:"Grammar",f:"Partitive (some/any)",b:"du (masc) · de la (fem) · de l' (before a vowel) · des (plural) = 'some'. Je mange du pain, de la viande, des pommes."},
  {t:"Grammar",f:"Possessive adjectives",b:"mon/ma/mes (my) · ton/ta/tes (your) · son/sa/ses (his/her) · notre/nos · votre/vos · leur/leurs. They agree with the thing owned, not the owner."},
  {t:"Grammar",f:"Comparatives",b:"plus … que (more than) · moins … que (less than) · aussi … que (as … as). e.g. plus grand que = taller than."},
  {t:"Grammar",f:"Expressions with 'avoir'",b:"avoir faim (be hungry) · avoir soif (thirsty) · avoir chaud/froid (hot/cold) · avoir … ans (be … years old) · avoir raison (be right)."},
  {t:"Vocab",f:"Le temps (weather)",b:"il fait beau (nice) · il fait mauvais (bad) · il pleut (raining) · il neige (snowing) · il fait chaud/froid · il y a du vent (windy)."},
 ],
 quiz:[
  {q:"'I am going to eat' (futur proche):",o:["Je mange","Je vais manger","J'ai mangé","Je mangerai"],a:1,w:"aller + infinitive."},
  {q:"Passé composé of 'parler' (I spoke):",o:["Je parle","J'ai parlé","Je vais parler","Je parlais"],a:1,w:"avoir + parlé."},
  {q:"'Nous' form of être (present):",o:["sommes","êtes","sont","suis"],a:0,w:"nous sommes."},
  {q:"Which verb uses ÊTRE in passé composé?",o:["manger","aller","finir","vendre"],a:1,w:"aller = movement → être."},
  {q:"Past participle of 'faire':",o:["fait","fais","faisé","fu"],a:0,w:"j'ai fait."},
  {q:"'-ER' verb 'vous' ending (present):",o:["-ons","-ez","-ent","-es"],a:1,w:"vous parlez."},
  {q:"'Ils' form of avoir:",o:["ont","avons","as","a"],a:0,w:"ils ont."},
  {q:"'She went' (agreement):",o:["elle est allé","elle est allée","elle a allé","elle va aller"],a:1,w:"être verb + feminine → allée."},
  {q:"How do you say 'I don't eat'?",o:["Je mange pas","Je ne mange pas","Ne je mange","Je pas mange"],a:1,w:"ne … pas around the verb."},
  {q:"Reflexive: 'I get up' =",o:["je lève","je me lève","me je lève","je lève me"],a:1,w:"je me lève."},
  {q:"'est-ce que' is used to…",o:["Make a negative","Ask a question","Give an opinion","Form the past"],a:1,w:"Question form."},
  {q:"Past participle of 'prendre':",o:["prendu","pris","prené","prendé"],a:1,w:"j'ai pris."},
  {q:"'Some bread' =",o:["le pain","du pain","un pain","des pain"],a:1,w:"Partitive: du pain."},
  {q:"'My sisters' =",o:["mon sœurs","ma sœurs","mes sœurs","son sœurs"],a:2,w:"Plural → mes."},
  {q:"'Taller than' =",o:["aussi grand que","plus grand que","moins grand que","très grand"],a:1,w:"plus … que."},
  {q:"'I am hungry' =",o:["Je suis faim","J'ai faim","Je fais faim","Je vais faim"],a:1,w:"avoir faim → j'ai faim."},
  {q:"'It's raining' =",o:["il fait beau","il pleut","il neige","il y a du vent"],a:1,w:"il pleut."},
  {q:"The indefinite article for a plural noun:",o:["le","des","la","un"],a:1,w:"des = some (plural)."},
 ]
}
};
